-- ====================================================================================================================
-- ANALYTICAL QUERIES
-- ====================================================================================================================

USE RetailSalesAndCustomerAnalyticsDB;

-- 1. Top 10 customers by total spending.

SELECT TOP 10 c.CustomerID,
       c.FirstName +' '+ c.LastName AS CustomerFullName,
       SUM(oi.Quantity * oi.UnitPrice) AS TotalSpending
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
Join OrderItems oi ON o.OrderID = oi.OrderID
GROUP BY  c.CustomerID, c.FirstName, c.LastName
ORDER BY TotalSpending DESC;

-- 2. Top 5 best-selling products by quantity sold.

SELECT TOP 5 p.ProductID,
       p.ProductName,
       SUM(oi.Quantity) AS QuantitySold
FROM Products p
JOIN OrderItems oi ON p.ProductID = oi.ProductID
GROUP BY p.ProductID, p.ProductName
ORDER BY QuantitySold DESC;

-- 3. Total revenue generated by each employee.

SELECT e.EmployeeID,
       e.FirstName + ' ' + e.LastName AS EmployeeFullName,
       SUM(oi.Quantity * oi.UnitPrice) AS TotalRevenue
FROM Employees e
JOIN Orders o ON e.EmployeeID = o.EmployeeID
JOIN OrderItems oi ON o.OrderID = oi.OrderID
GROUP BY e.EmployeeID, e.FirstName, e.LastName ;

-- 4.  Monthly sales revenue for the business.

SELECT YEAR(OrderDate) AS Year,
        MONTH(OrderDate) AS Month,
        SUM(Quantity * UnitPrice) AS MonthlySalesRevenue
FROM Orders o
JOIN OrderItems oi ON o.OrderID = oi.OrderItemID
GROUP BY YEAR(OrderDate),MONTH(OrderDate)
ORDER BY Year, Month;

-- 5. Number of orders placed each day.

SELECT DAY(OrderDate) AS Day,
       COUNT(OrderID) AS TotalOrders
FROM Orders
GROUP BY  OrderDate
ORDER BY OrderDate;


-- 6. Products that have never been ordered.

SELECT ProductName
FROM Products p
WHERE NOT EXISTS (
    SELECT 1
    FROM OrderItems oi
    WHERE oi.ProductID = p.ProductID
);

-- 7. Customers who have placed more than 1 orders.

SELECT c.CustomerID, c.FirstName + ' ' + c.LastName AS CustomerFullName,
       COUNT(o.OrderID) AS TotalOrders
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName
HAVING COUNT(o.OrderID)  > 1;

-- 8. Revenue contribution by product category.

SELECT p.Category,
       SUM(oi.Quantity * oi.UnitPrice) AS TotalRevenue
FROM Products p
JOIN OrderItems oi ON p.ProductID = oi.ProductID
GROUP BY p.Category;

-- 9. Orders with total value greater than 5000.

SELECT OrderID,
       SUM(Quantity * UnitPrice) AS TotalValue
FROM OrderItems
GROUP BY OrderID
HAVING  SUM(Quantity * UnitPrice) > 5000
ORDER BY TotalValue DESC;


-- 10. Average quantity ordered per product.

SELECT ProductID, 
       AVG(Quantity) AS AverageQuantity
FROM OrderItems
GROUP BY ProductID;
