-- ===================================================================================================================
-- BASIC QUERIES 
-- ====================================================================================================================

USE RetailSalesAndCustomerAnalyticsDB;

-- 1.Total revenue generated by the store.

SELECT SUM(Quantity * UnitPrice) AS TotalRevenueGenerated
FROM OrderItems oi
JOIN Orders o ON oi.OrderID = o.OrderID;

-- 2. Total number of orders placed by each customer.

SELECT COUNT(o.CustomerID)  AS TotalOrders,
       c.FirstName + ' ' + c.LastName AS CustomerName
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
GROUP BY o.CustomerID, c.FirstName, c.LastName;

-- 3. List all completed orders with customer name and employee responsible.

SELECT o.OrderID,
       c.FirstName + ' ' + c.LastName AS CustomerName,
       e.FirstName + ' ' + e.LastName  AS EmployeeName
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
JOIN Employees e ON o.EmployeeID = e.EmployeeID
WHERE o.OrderStatus = 'Completed';

-- 4. Total number of products sold per category.

SELECT Category, SUM(Quantity) AS TotalNumberOfProducts
FROM Products
GROUP BY Category;

-- 5. Average order value across all completed orders.

WITH OrderTotal AS (SELECT COUNT(*) AS TotalOrders
FROM Orders
WHERE OrderStatus = 'Completed'
)
SELECT AVG(TotalOrders) AS  AverageOrderValue
FROM OrderTotal;